project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

website:
  title: "Zaineb Smida"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - Teaching.qmd

format:
  html:
    theme: 
      dark: solar
    css: styles.css
    toc: true
    page-layout: full
editor: visual

